Rc v1.12.3 - Removed Bus routes logic
UCF/Campus-Map pull request #7
Opened 2017-03-06 21:23 UTC by rjucf

2017-03-06 21:40 UTC, cjg89 approved these changes

2017-03-06 21:59 UTC, keeeeeegan approved these changes

2017-03-07 18:33 UTC, jmbarne3 approved these changes

2017-03-07 19:15 UTC, cjg89 requested changes

2017-03-07 19:15 UTC, cjg89 commented on static_files/js/map.js
> +	$('.ga-tracking').live('mousedown', trackClick);
Using `.delegate()`, particularly for the old version of jquery that Map is running on, is preferred over `.live()`:  http://api.jquery.com/live/#entry-longdesc

2017-03-07 20:34 UTC, cjg89 approved these changes

2017-03-13 13:57 UTC, merged